---
- name: Install cuckoo
  hosts: localhost
  user: root
  # remote_user: user
  # sudo: yes
  vars:
    - cuckoo_version: "2.0.6"
    - install_dir: "cuckoo"

  roles:
    - virtualbox
    - cuckoo
